name: geomky
description: "GeoMKY"
# 以下行可防止使用`flutter pub publish`意外将包发布到pub.dev。对于私有包推荐此设置。
publish_to: 'none' # 如果希望发布到pub.dev，请删除此行

# 以下定义应用程序的版本号和构建号。
# 版本号是三个用点分隔的数字，如1.2.43
# 后面可以跟一个可选的构建号，用+号分隔。
# 在flutter构建时，可以通过指定--build-name和--build-number来覆盖版本号和构建号。
# 在Android中，build-name用作versionName，而build-number用作versionCode。
# 有关Android版本控制的更多信息，请访问 https://developer.android.com/studio/publish/versioning
# 在iOS中，build-name用作CFBundleShortVersionString，而build-number用作CFBundleVersion。
# 有关iOS版本控制的更多信息，请访问
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# 在Windows中，build-name用作产品和文件版本的主版本、次版本和修订版本部分，而build-number用作构建后缀。
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# 依赖项指定您的包工作需要其他哪些包。
# 考虑运行`flutter pub upgrade --major-versions`自动将包依赖项升级到最新版本。
# 或者，可以通过将下面的版本号更改为pub.dev上的最新版本手动更新依赖项。
# 要查看哪些依赖项有较新版本可用，请运行`flutter pub outdated`。
dependencies:
  flutter:
    sdk: flutter

  # 用来在 Flutter 中运行 OpenGL ES Shader
  flutter_gl: ^0.0.7   # 最新版请查 pub.dev

  ffi: ^2.1.2

  # 以下将Cupertino Icons字体添加到您的应用程序中。
  # 与CupertinoIcons类一起使用可获得iOS风格图标。
  cupertino_icons: ^1.0.8

  #
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 下面的"flutter_lints"包包含一组推荐的lint规则，
  # 以鼓励良好的编码实践。该包提供的lint规则集在您包根目录的
  # `analysis_options.yaml`文件中被激活。有关停用特定lint规则
  # 和激活其他规则的信息，请参阅该文件。
  flutter_lints: ^5.0.0

# 有关此文件中通用Dart部分的信息，请参阅
# 以下页面：https://dart.dev/tools/pub/pubspec

# 以下部分特定于Flutter包。
flutter:

  fonts:
    - family: Maple  # 定义字体家族名称
      fonts:
        - asset: assets/fonts/MapleMono-Regular.ttf  # 指向字体文件的路径

  assets:
    - assets/shaders/fragment.glsl

  # 以下行确保Material Icons字体包含在您的应用程序中，
  # 以便您可以使用material Icons类中的图标。
  uses-material-design: true

  # 要向应用程序添加资源，请添加一个assets部分，如下所示：
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # 图像资源可以引用一个或多个特定分辨率的"变体"，请参阅
  # https://flutter.dev/to/resolution-aware-images

  # 有关从包依赖项添加资源的详细信息，请参阅
  # https://flutter.dev/to/asset-from-package

  # 要向应用程序添加自定义字体，请在此处的"flutter"部分添加fonts部分。
  # 此列表中的每个条目应有一个"family"键指定字体系列名称，
  # 和一个"fonts"键指定字体的资源路径和其他描述符列表。
  # 例如：
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # 有关从包依赖项添加字体的详细信息，
  # 请参阅 https://flutter.dev/to/font-from-package